### ISSUE TITLE
Can't connect to tenant

### ISSUE THREAD

**Issue by ChernykhAN** [ulranh/hana_sql_exporter#3]
I having error after set password.
Command:
```
 ./hana_sql_exporter pw --tenant c01 --config ./hana_sql_exporter.toml
```

after password entered
```
Password: time="02-11-2020 21:54:44" level=error msg="Can't connect to tenant" error="dial tcp: missing address" tenant=c01
```

I have tried with ip and host-name in ConnString in config
```
[[tenants]]
  ConnString = "10.10.10.30:32015"
  Name = "c01"
  Tags = ["sapabap", "abap"]
  User = "myuser"
```

The secret has been writen in toml config despite getted error. 
And [[tenants]] section has been moved after [[metrics]] section.

**Comment by ulranh** [comment]
Is 31010 the SQL Port of the Tenant? You can determine the SQL Port with:

`select host,service_name,port,sql_port from sys.m_services
`

**Comment by ChernykhAN** [comment]
Yes, it's correct port, I'v successfully connected to this host:port in Hana Studio. Instance 20.

PS, Sorry, my mistake, I used port 32015. The same port in table sys.m_services only in one raw:
chq-db	indexserver	32003	32015
all other rows have 0 SQL port.

**Comment by ulranh** [comment]
I just saw that you have ConnString in your toml file. It must be ConnStr. This has changed some time ago but I unfortunately inserted the old notation again in the README.

**Comment by ChernykhAN** [comment]
Now it's connecting successfully. 
Thanks a lot.
